# Generated by Django 4.1.7 on 2023-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vgame_name', models.CharField(max_length=30)),
                ('developer_name', models.CharField(max_length=30)),
            ],
        ),
    ]
